name: Node.js CI
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: delete useless directory
        run: sudo rm -rf .git .github
      - name: upload original file
        uses: actions/upload-artifact@v4
        with:
          name: certs
          path: ./

      # - name: build zip file
      #   run: |
      #     7z a -tzip certs.zip `ls -1`
      # - name: upload zip file
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: certs
      #     path: certs.zip
